### ISSUE TITLE
keyboard layout Additional Request

### ISSUE THREAD

**Issue by natura4917** [AppGround-io/bluetooth-keyboard-and-mouse-support#10]
I'd like to request to add a Korean keyboard layout.
two sets of Hangul

**Comment by ricardohnn** [comment]
I agree... Swype feature would be very welcome... So if possible to be able to change ime would means to be able to use gboard keyboard and hence other keyboards.

**Comment by AppGround-io** [comment]
Korean layout and Swype is now supported

**Comment by natura4917** [comment]
think you
