### ISSUE TITLE
Samsung s20 fe connecting to Windows 10 failure

### ISSUE THREAD

**Issue by twistedddx** [AppGround-io/bluetooth-keyboard-and-mouse-support#102]
I have previously used this app on a Sony XZ2 connecting to Windows 10 and it worked perfectly.
I now have a Samsung S20 FE 5g and it entirely does not work.

I have paired the S20 FE to Win10 machine numerous times.
When I open this app and go to Bluetooth connection screen it either says the Bluetooth connection may not be usable or it says the devices are successfully paired but the app is in a disconnected state.
Pressing connect never connects the devices.

The app mentioned to remove and readd on the remote device, which I have done endless times.
The app and this github also sometimes refers to compatibility mode which I simply cannot find in the app.
Perhaps this setting was removed recently?

This issue exist for my s20 FE on Android 10 and continues with Android 11 update.

**Comment by AppGround-io** [comment]
I would like to find out if this is problem with the app or with one of the devices.

Do you have a device that you can connect to from your Samsung S20 FE? 

My first guess would be that this is a problem with the Windows PC as Bluetooth is really good on the Samsung devices in general and Bluetooth on Windows can be a hit or miss.

**Comment by twistedddx** [comment]
I think I have it worked out.

I was switching apps on the s20fe between VNC to control the Windows machine and BleK.
It appears BleK must remain focused during pairing on the s20fe or BleK pairing will fail.
When failed Windows 10 would show the s20fe paired as a POS Printer device and would list that the s20fe could do 6 services including audio and handsfree etc. But it did not list the "Drivers for keyboard, mice, etc (HID)" service.

With s20fe keeping BleK pairing screen in focus and Sony XZ2 running VNC I was able to successfully add the s20fe

I am able to do the VNC/BleK switching on my Sony XZ2 while adding the Sony XZ2 to the Windows 10 box.
Perhaps Sony doesn't suspend the background app?

For testing I also connected a Realme X2. The compatibility mode setting was shown, but needed to be turned off to work.
The Realme X2 had what appeared 2 connections going and asked to be paired with 2 different pairing pins.
I did not attempt the VNC/BleK switching on this device. BleK was on the Realme and VNC was running on Samsung device.


The Windows 10 machine was tested with CSR 4.0 and Realtek 5.0 USB dongles. Both function the same for all devices.

**Comment by twistedddx** [comment]
For reference this is what successful BleK pairings look like in Windows 10.
The "SAMSUNG" audio device is the TV connected via HDMI and not the s20fe.

<img width="960" alt="realme_x2" src="https://user-images.githubusercontent.com/12379314/107496942-dc229680-6be1-11eb-92c6-92bfe2bcddb0.PNG">
<img width="960" alt="samsung_s20fe" src="https://user-images.githubusercontent.com/12379314/107496952-dd53c380-6be1-11eb-8840-a02146b35b01.PNG">
<img width="960" alt="sony_xz2" src="https://user-images.githubusercontent.com/12379314/107496954-ddec5a00-6be1-11eb-993b-90c83ae77c4a.PNG">
