### ISSUE TITLE
Touch Pad in Custom Mode

### ISSUE THREAD

**Issue by dluigi** [AppGround-io/bluetooth-keyboard-and-mouse-support#103]
**Is your feature request related to a problem? Please describe.**
1. I only use the custom mode and create only buttons I need but there is no touchpad AND button to open my phone keyboard to add from the list that works like the touch pad AMD keyboard button like in Mouse/Keyboard Mode.
2. Even if my keyboard is in Hebrew - the PC will keep typing in English. I found a solution in the Custom mode by adding a button that when you press on it - it switches language by pressing SHIFT+ALT, but it's not comfortable like swapping righ/left on my phone keyboard in order to simply switch language.

**Describe the solution you'd like**
Add those options :)

**Comment by AppGround-io** [comment]
With the new beta version it is now possible to add a touch pad in custom mode.
