### ISSUE TITLE
"Pairing may not be usable"

### ISSUE THREAD

**Issue by th3v4n** [AppGround-io/bluetooth-keyboard-and-mouse-support#104]
I can connect to my laptop but not my desktop. Both are running Win10 x64. The error I get from the app says that the "pairing might not be usable".

Phone is a Samsung A5 2017, Android 8.0.

Any ideas or tips for troubleshooting this?

Thanks.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AppGround-io** [comment]
Please remove the Bluetooth pairing and try to connect to your device again.
