### ISSUE TITLE
Keyboard only option

### ISSUE THREAD

**Issue by havealoha** [AppGround-io/bluetooth-keyboard-and-mouse-support#11]
When I connect to my iPhone, I want the ability of the Android to show a full screen keyboard. The touch pad does no good for an iPhone.

**Comment by havealoha** [comment]
Oh, duh, there is already an issue like this. What is the procedure?

**Comment by AdamKane41** [comment]
#6

**Comment by AdamKane41** [comment]
@havealoha Just click the red "close issue' button below (next to the green" comment" button...)
Peace
