### ISSUE TITLE
App Start asking for update

### ISSUE THREAD

**Issue by Dragon1306245** [AppGround-io/bluetooth-keyboard-and-mouse-support#112]
App asking to update to last version, but last version already install. Samsung Note 10 + Android 11.
Using premium version. Please fix it

![Screenshot_20210328-151934_Bluetooth Keyboard   Mouse](https://user-images.githubusercontent.com/60705639/112753752-426c4880-8fd9-11eb-9736-a263e4145594.jpg)

**Comment by AppGround-io** [comment]
Please try to remove the app and install it again from the Play Store.
