### ISSUE TITLE
IPhone version

### ISSUE THREAD

**Issue by havealoha** [AppGround-io/bluetooth-keyboard-and-mouse-support#12]
I have looked and looked and can't find an app like this for an iPhone to act as a serverless keyboard. "Unified remote" and "Mobile Mouse Remote" come close but are meant for desktop OS's. This app works great as a Bluetooth keyboard for an iPhone. Please develop a version for iPhone to act as keyboard for Android.

**Comment by AppGround-io** [comment]
Unfortunately there are no APIs available on iOS to do this kind of app, so a iPhone version is not possible yet.
