### ISSUE TITLE
The cursor stops immediately.

### ISSUE THREAD

**Issue by tazn246** [AppGround-io/bluetooth-keyboard-and-mouse-support#13]
Hi
I connect to Android 8 tablet from Android 9 smartphone, the cursor can be manipulated for a few seconds, but it stops after a while. It seems to stop when I try to move while tapping hard. What should I do?
Thank you, the app is great!

**Comment by AppGround-io** [comment]
Please try the current version, there are a lot of improvement for the connection. If you still have problems, let me know.
