### ISSUE TITLE
works to control android, but when I enter kodi I can't click 

### ISSUE THREAD

**Issue by mg1234567** [AppGround-io/bluetooth-keyboard-and-mouse-support#15]
Within Kodi 18.5 on Android, I cannot click anything. 
The mouse on screen will move to icons etc but will not click on anything.  
For example, I try to hit the settings kog the mouse will move around and if I try to click on something (both with or without dedicated buttons) the icon will pulse (white to standard) but never turn white or get actually clicked. 
It's as if clicking on the cog sort of half clicks and never fully depresses the icon.   
The icon will just sort of pulse under the mouse while I hit it, but never selects.  

With another connected device (mouse / keyboard), if I select the cog icon under the mouse (using arrows / mouse) it will turn white and be awaiting input.  Then, using the app, if I hit the mouse button on the app (dedicated or not) it will de-select (remove the white highlighting).  It just sort of pulses (again like a half click). 

FYI if I connect a regular mouse or keyboard, I CAN click on icons and properly navigate Kodi 
Question: is there something I need to do within kodi to get this to work or does this need to be fixed?

**Comment by mg1234567** [comment]
Also the same if connected via Bluetooth LE...

**Comment by AppGround-io** [comment]
Please try again with the new version, should be fixed now.
