### ISSUE TITLE
Google Keyboard missing navigation keys (top row with GIF / ,.. options) 

### ISSUE THREAD

**Issue by mg1234567** [AppGround-io/bluetooth-keyboard-and-mouse-support#16]
I use google keyboard... normally, there is a row on top of the letters (numbers too, if you have that enabled). 
This row shows: G, animated gifs, GIF, clipboard, settings cog, ... 

Anyway, the "..." option has another option for "Text Editing" 

This "Text Editing" brings up arrows keys, select, copy, paste, etc... 
These keys are useful for navigating easily... 

In your implementation of "keyboard" this row is missing / not available.  

Please help!

**Comment by AppGround-io** [comment]
This should now be solved with the input bar in the bar
