### ISSUE TITLE
Suggestion: add windows key and more

### ISSUE THREAD

**Issue by Ek-Andreas** [AppGround-io/bluetooth-keyboard-and-mouse-support#17]
This app works pretty well especially when you connect your laptop to a big screen

But it woukd make it easier if there was a dedicated escape, windows key, alt-tab macro key and customizable macro keys
Like set up an alt f4 or a ctrl-w key etc. 
Would make premium more enticing

**Comment by AppGround-io** [comment]
It's now possible to create shortcuts for single keys and key combinations in the premium version of the app.
