### ISSUE TITLE
Arrow keys for android 

### ISSUE THREAD

**Issue by onukomer** [AppGround-io/bluetooth-keyboard-and-mouse-support#18]
App is works well, i just purchased the app and features are very useful.
Sometimes mouse is not enough for android TV boxes. Please add the following keys : up, down, left, right and OK.

Congrats for the app again.

**Comment by zorazor** [comment]
I can recommend the app/keyboard "Hacker's Keyboard":

![Screenshot_20200203-175959_Bluetooth Keyboard   Mouse](https://user-images.githubusercontent.com/54184078/73673718-6ec75600-46af-11ea-875e-f6ebb47af03a.jpg)

**Comment by onukomer** [comment]
Thanks for advice. But I mean on screen buttons or bottom of the 3 buttons (back, home, menu) maybe a bit more useful for us

**Comment by RadicalMonkey** [comment]
@AppGround-io  Is there any chance of adding this? With this functionality this app becomes the only app needed to control an Android TV device

**Comment by RadicalMonkey** [comment]
Its not ideal to install random keyboards to get this functionality so please consider this

**Comment by onukomer** [comment]
I think latest update is enough for adding the new keys :) I'm happy with it. Thanks

**Comment by AppGround-io** [comment]
New multimedia mode is available in 2.8.3

![device-2020-06-08-095145](https://user-images.githubusercontent.com/50548429/84136978-4def8280-aa4c-11ea-81c9-12b862da0529.png)
