### ISSUE TITLE
Pressing Shift key on a Hardware Keyboard leads to deleton

### ISSUE THREAD

**Issue by alexanderadam** [AppGround-io/bluetooth-keyboard-and-mouse-support#19]
If the shift key was pressed it somehow deletes everthing (even if I stop using the shift key). This means I can't type uppercase letters or characters that require shift.
This happens on [Samsung S4 Tablet](https://www.samsung.com/global/galaxy/galaxy-tab-s4/) with the [original Samsung Keyboard cover](https://www.samsung.com/us/mobile/mobile-accessories/tablets/galaxy-tab-s4-book-cover-keyboard-ej-ft830ubeguj/).

The hardware keyboard works everywhere else and using your app with a software keyboard works as well.

**Comment by AppGround-io** [comment]
This should be fixed with the latest version of the app.
