### ISSUE TITLE
Scroll wheel option / Typing text box / TV back button bug

### ISSUE THREAD

**Issue by abhishekabhi789** [AppGround-io/bluetooth-keyboard-and-mouse-support#21]
Hi, please add a vertical scroll bar for easy sliding.(on the right side of the mouse screen) Two finger gesture can't easily used when holding the phone with one hand.

If Long press on keyboard icon will open a temporary text box, where gesture typing is possible and after clicking ok/send button sends those text like 'paste clipboard text' will be helpful.

Also back button function on android navigation bar not working for mi tv 4a, right click button and gesture works

**Comment by AppGround-io** [comment]
Please let me know if you miss anything from the list in the current version of the app.
