### ISSUE TITLE
Video stop when minimize remote apps

### ISSUE THREAD

**Issue by xplunk** [AppGround-io/bluetooth-keyboard-and-mouse-support#22]
I use this bluetooth remote apps to control my video streaming app in android tv. It works perfectly. But after i select my video and play, i put this remote app to minimize and suddently the video on tv also stopped. 

How to fix this?

**Comment by AppGround-io** [comment]
Some apps have a problem when a Bluetooth device is disconnected. With the new (beta) version, the  connection will stay if the app is in the background, this should fix your problem.

**Comment by AppGround-io** [comment]
This problem should be fixed now
