### ISSUE TITLE
Suggestion: Samsungs Devices with S-Pen 

### ISSUE THREAD

**Issue by krheinwald** [AppGround-io/bluetooth-keyboard-and-mouse-support#23]
Would love to be able to use my tablet with pen as a Windows pen for handwriting, drawing, etc. 

Should react to the pen only, without disturbance by accidental touches of the screen.

Extra features of the pen (touching the screen = left click, pen button = right click) would be great, so would be 'function soft keys* to e.g. bring up the Windows Whiteboard.

**Comment by AppGround-io** [comment]
This is definitely a feature I want to have as well, but I can not give a date yet when it will be implemented.

**Comment by parkerlreed** [comment]
Loving them recently added pen support. 

Not sure if possible over just Bluetooth HID, but would be great to have it as an absolute drawing tablet. Maybe an option in the pen settings to set the target device screen resolution and then map the touchpad area 1:1 when using the pen.
