### ISSUE TITLE
ctrl+z / ctrl+y and other combos are switched on german keyboard layout

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-keyboard-and-mouse-support#24]
Hello,

single z/y letters are working as expected.
But the key combinations ctrl+z / ctrl+y are switched on german keyboard layouts. 

(I'm sorry about this ridiculous request, but I'm using this shortcut keys very often.

And the new foreground service from the last update is awesome. Thank you!)

**Comment by AppGround-io** [comment]
Thanks for the report, I found the problem and it will be fixed in the next version.

**Comment by zorazor** [comment]
Thank you, maybe you can fix the zoom-hotkeys, too? :)

ctrl and +
ctrl and -

**Comment by zorazor** [comment]
Thank you for the update. Most shortcuts are working now :)

"**ctrl and -**" is unfortunately still missing.

**Comment by zorazor** [comment]
Thank you for the update.

**"ctrl and +"** is unfortunately still missing.
I tested the KeyPress-Event with xev.

Result for **ctrl and +**:
**Control_L**, keycode 37 (keysym 0xffe3)
"**<**", keycode 94 (keysym 0x3c)

**Comment by AppGround-io** [comment]
This is fixed with version 2.7.0 rolling out today
