### ISSUE TITLE
Android 6 support

### ISSUE THREAD

**Issue by enveraltin** [AppGround-io/bluetooth-keyboard-and-mouse-support#26]
Hey,

I've got a spare Blackberry Priv which also has a physical keyboard, it still runs Android 6.0 and can't be upgraded and unfortunately I can't install this app on It.

It would be awesome if you could support Android 6.

Thanks!

**Comment by zorazor** [comment]
Unfortunately you need at least an Android 9 device.
Android 9 (API level 28) added support for bluetooth HID device profiles.

**Comment by enveraltin** [comment]
I see, thanks!
