### ISSUE TITLE
Keep display on during full screen track pad mode

### ISSUE THREAD

**Issue by enveraltin** [AppGround-io/bluetooth-keyboard-and-mouse-support#28]
Usually devices go into timeout and turn the display off to save power. This makes sense but when using the device as a trackpad this feature becomes a bit disturbing. I have to unlock my phone way too many times when I'm using it as a trackpad.

It would be awesome if the app could keep the display on when in full screen track pad mode.

**Comment by AppGround-io** [comment]
The option to keep the screen on is now available in the settings of the app
