### ISSUE TITLE
Does not work with Samsung Galaxy Tab A 2019 and Windows 10

### ISSUE THREAD

**Issue by jgrzymisch** [AppGround-io/bluetooth-keyboard-and-mouse-support#30]
Works with my Samsung Galaxy S9 and my Windows 10 laptop, but it does not work with my Samsung Galaxy Tab A (2019) and the same Windows 10 Laptop. 

Any ideas? 

Thanks!

**Comment by denilsonsa** [comment]
I'm not the developer, but I just managed to use the app with Samsung Galaxy Tab A 2019 (model T510) together with a Windows 10 laptop. If your tablet is already paired with the laptop, you may need to first unpair it (i.e. remove it from windows bluetooth devices list).

**Comment by AppGround-io** [comment]
Please try again with the newest app version, should work much better now.
