### ISSUE TITLE
Left/Right click don't work on trackpad

### ISSUE THREAD

**Issue by zakirk88** [AppGround-io/bluetooth-keyboard-and-mouse-support#35]
It's a multitasking issue like if you want to hold and drag something, you need to hold the button and use trackpad to move items.

The problem is when you enable the manual buttons for left and right click, click feature on trackpad doesn't work. This needs to be fixed. Just like actual trackpads this should work both the manual buttons enabled.

**Comment by zorazor** [comment]
i like it that trackpad clicks are disabled, if the mouse buttons are enabled.

**Comment by zakirk88** [comment]
> i like it that trackpad clicks are disabled, if the mouse buttons are enabled.

Yes but that's not how you use trackpad on Laptop, if you remember correctly. And most people are accustomed to that way only. Even with manual buttons enabled, there should be basic functionality of clicks available on trackpad.

**Comment by zorazor** [comment]
I get on fast movements sometimes drag & drop misentries, if trackpad clicks are enabled. So most of the time I'm using the buttons.

Maybe it could be enabled/disabled as an optional function in the mouse settings.

**Comment by zakirk88** [comment]
> I get on fast movements sometimes drag & drop misentries, if trackpad clicks are enabled. So most of the time I'm using the buttons.
> 
> Maybe it could be enabled/disabled as an optional function in the mouse settings?

Yes that would be really great. It would definitely single this app out.

**Comment by AppGround-io** [comment]
I added a option to enable/disable touchpad mouse clicks in the new version 2.7.0

**Comment by zakirk88** [comment]
Thnx a lot. That makes it even more awesome.
