### ISSUE TITLE
unable to upgrade to premium

### ISSUE THREAD

**Issue by OTSUKAKK** [AppGround-io/bluetooth-keyboard-and-mouse-support#36]
Thank you for creating such great app!!
I press the Upgrade to premium,  but nothing happen.
Uninstall and install several times, it still no work.

*I have try another app's in-app purchase in the same phone,the confirmation window is show up functionally.

Could you please enable the Premium Paid Version for purchase in Hong Kong?
Thank you.

**Comment by AppGround-io** [comment]
The app is now available
