### ISSUE TITLE
Ubuntu support?

### ISSUE THREAD

**Issue by zlobec** [AppGround-io/bluetooth-keyboard-and-mouse-support#37]
Any suggestion how to get the app to work with Ubuntu distributions?

**Comment by zorazor** [comment]
it'I works flawlessly on Linux (Ubuntu, Debian, Arch, Manjaro...).
BlueZ is preinstalled on most distributions.

**Comment by zlobec** [comment]
Here's my experience.

I'm running the app on Android 8.0. in compatibility mode. Pairing is successful to my Ubuntu Budgie 18.04 device. And when connecting is says connected. But Ubuntu pairs as type Phone... not HID. And thus it does not work.

Then I was unsure about the Bluetooth module compatibility and installed on the same device a Windows 10 installation. Pairs as HID, starts working and immediately says not connected, but still works... then after 2 minutes wants to pair again as Phone and after successful pairing (as phone), does not work any more. After 2-3 attempts of re-pairing as HID I get it to work, but then Windows does not recognize the phone anymore - cant pair in any mode. I guess Windows blocks the device, or sth, because I can still pair on Ubuntu (2nd device).

So I conclude, that although its Android 8.0 it can pair to my Bluetooth module, but just not in Ubuntu. How do I trick Ubuntu to pair as HID not Phone?

**Comment by zorazor** [comment]
This is probably because your smartphone still has Android 8.

You could try to change the device class manually. But I'm not 100% sure if it works...

If your smartphone isn't paired, pair it first.
But it shouldn't be connected at this point.

Then edit on your ubuntu system the "info" file (e.g. with nano):
/var/lib/bluetooth/YOUR_LINUX_BTMAC/YOUR_SMARTPHONE_BTMAC/info

And change the class to **0x5a020c**

**Comment by zlobec** [comment]
And I do blame my phone :D

The Device Class is 0x5a020c and even if I try to change it anything other (peripheral), when it reconnects it reverts it back to default. Service restart or reboot does not change this behavior.

I'll mark this as resolved, and I'll just get an Android 9 phone ;D
