### ISSUE TITLE
Enable swipe in keyboards

### ISSUE THREAD

**Issue by ricardohnn** [AppGround-io/bluetooth-keyboard-and-mouse-support#38]
It would definitely help if you were able to swipe words using gboard.
I am currently using on pixel 2xl and paired on an ipad 6th gen

**Comment by zorazor** [comment]
Have you tried to press space after a swiped word? On the default samsung keyboard it's working well.

**Comment by ricardohnn** [comment]
Really? I just tried here with both gboard and just installed swiftkey... Can't swipe... At all... Doesn't even show swiping

**Comment by zorazor** [comment]
It seems to work currently only with the samsung keyboard. I just tried it with the gboard and swiping is also disabled.

**Comment by AppGround-io** [comment]
With the new input bar swiping keyboards are now supported
