### ISSUE TITLE
Disable Vibration While Scrolling

### ISSUE THREAD

**Issue by fadh99** [AppGround-io/bluetooth-keyboard-and-mouse-support#40]
Is it just me or not, the phone will vibrating when :
- using two fingers for scrolling (at every gesture movement )
- double-clicking
- single-clicking
Is it any setting to turn this off? Bcos I cant find it...
.
Im using Xperia X Compact.

**Comment by zorazor** [comment]
unfortunately you need to disable system wide vibrations for "interaction controls".

**Comment by fadh99** [comment]
Ah ok, thanks for the reply. Problem solved now
