### ISSUE TITLE
Mouse Clicks with Modifiers (Ctrl, Alt, Shift)?

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-keyboard-and-mouse-support#41]
Is it possible to add modifiers for mouse clicks?

e.g.:
Ctrl + Mouse Click
Alt + Mouse Click
Shift + Mouse Click

or combinations like:
Ctrl+Shift + Mouse Click
Ctrl+Alt+Shift + Mouse Click

**Comment by zorazor** [comment]
I would like to add that similar keyboard combos/modifiers without mouse are working fine:
SHIFT+DEL
CTRL+ARROWRIGHT
ALT+SPACE
CTRL+ALT+DEL
...

**Comment by WalkingDot** [comment]
Yay, this is absolutely necessary. For some tasks I have to switch to a real wireless keyboard/trackpad.

Seems to be a minor bug. The left and right mouse buttons are also sent simultaneously.

**Comment by zorazor** [comment]
@WalkingDot 
Thanks for the hint! Nice to have MiddleClick-Simulation :)

**Comment by zorazor** [comment]
@AppGround-io 
Have you maybe had some time to test combinations with mouse clicks?
It would be great to be able to use all functions of e.g. Gimp or Office/Calc.

**Comment by zorazor** [comment]
Amazing! I just happened to notice that combinations with mouse clicks are now supported.

Thank you so much!
