### ISSUE TITLE
Shortcut Selection: 6 is missing

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-keyboard-and-mouse-support#42]
The 6 is missing at the Shortcut-Selection ;-)

**Comment by ricardohnn** [comment]
Well noticed lol...

**Comment by ricardohnn** [comment]
Why was this closed?

**Comment by zorazor** [comment]
@ricardohnn 
sry, this was a mistake. I reported it...

**Comment by zorazor** [comment]
Thank you for the fix (v 2.8.0).
