### ISSUE TITLE
App suggestion

### ISSUE THREAD

**Issue by rdhiviyan** [AppGround-io/bluetooth-keyboard-and-mouse-support#51]
Additional of game pad controls to act as virtual gamepad

**Comment by AppGround-io** [comment]
There is now a dedicated app for Bluetooth Gamepad. Currently only works on selected devices and you need to create a new Bluetooth connection when you already used the normal keyboard & mouse app.

https://play.google.com/store/apps/details?id=io.appground.gamepad

Support forum:
https://github.com/AppGround-io/bluetooth-gamepad-support

Here some codes to get the app for free:

> https://play.google.com/redeem?code=MNLNR93WQDLXTPHWX28YTPD
https://play.google.com/redeem?code=J0BKR2UXPH39V609JD64K1Z
https://play.google.com/redeem?code=T8AT9VJDNN2ZALJWFNFND4X
https://play.google.com/redeem?code=T8P7JALYSDD1XZL1Z7B6J9P
https://play.google.com/redeem?code=35WPHG0LPYUNFZY1N19HDEN
https://play.google.com/redeem?code=GGPWZMPEWFH1LMF3BM9K6AE
https://play.google.com/redeem?code=E8HQ6RA12CYXYBV7GAGN0ED
https://play.google.com/redeem?code=727VR1PBZBY5R61U48B9ZYG
https://play.google.com/redeem?code=7YHWPXEWLPJLRGLH843XCKU
https://play.google.com/redeem?code=67MZJR1MUSPWDVLBCU98TXQ
