### ISSUE TITLE
No mouse buttons

### ISSUE THREAD

**Issue by dutch2000** [AppGround-io/bluetooth-keyboard-and-mouse-support#56]
Hi
I am trying the free version ae moment. I am using a Huawei P30 running Miui 10.0.0 to connect to a windows 10 pc.
The problem is that the mouse buttons do not apperar on the phone as per the pictures shown in the play store.
Otherwise an excellent app, Thanks

**Comment by zorazor** [comment]
You have to enable the mouse buttons in the mouse settings.

**Comment by AppGround-io** [comment]
Dedicated mouse buttons is a premium feature and can be enabled in the settings.
