### ISSUE TITLE
Feature Request - Option for Mouse Button Positioning at the Top of the Screen (In Full Screen Touch Pad Mode)

### ISSUE THREAD

**Issue by nem1515** [AppGround-io/bluetooth-keyboard-and-mouse-support#57]
This is an Excellent piece of software.  Since discovering, I have actually stopped using mice because this software is more easier and comfortable to use for extended periods.  When I am able to work in the office again, I will be able to leave behind the mouse, mouse mat and spare batteries.  A bonus when travelling by air and living out of a small carry on bag.  I have one very big request that I think would greatly improve the ergonomics and will help other users:

In "Full Screen touch pad mode", would it be possible to have the option to have the Left/Right mouse buttons appear at the "Top" of the screen and even "Top+Bottom" at the same time (like HP Elite Book trackpad)?

This would help with using the Right mouse button which when placed at the "Bottom" is made difficult to use by the need for twisting of the wrist and looking away from the screen in order to position thumb or middle finger to reach it.  Also button at the top would allow for more secure grip when using as an "Air Mouse", you can grip the phone from the sides more securely and use index finger to reach buttons instead of having to resting the phone in a top-heavy way in your hand increasing the risk of the phone toppling and dropping on the floor.

Many thanks.

**Comment by AppGround-io** [comment]
Coming soon...
![image](https://user-images.githubusercontent.com/50548429/88278055-10844300-cce2-11ea-8669-84c2fb90ba94.png)

**Comment by AppGround-io** [comment]
The option is available in the current beta version of the app.

**Comment by AppGround-io** [comment]
Released
