### ISSUE TITLE
mousedown,mouseup variation

### ISSUE THREAD

**Issue by nagesh66542** [AppGround-io/bluetooth-keyboard-and-mouse-support#58]
1.how to manipulate mouse up mouse down functions,
2.how to use this app to drag an item.
3.how to use this app like touch scroll in a touch screen interface.
4.make a windows keyboard or enable to change keyboard for this app from installed keyboards.

i am bought premium app.
if the above function are already there, 

please comment how to activate.

**Comment by AppGround-io** [comment]
You can enable the dedicated mouse button in the settings menu to click and drag items. 
Scrolling is possible with two fingers or with one finger on the right side of the screen.
For feature requests, please create a issue for each feature.

**Comment by nagesh66542** [comment]
Thanks for reply,
make a windows keyboard or enable to change keyboard for this app from installed keyboards.

**Comment by AppGround-io** [comment]
Please open a new issue for the feature request, will be easier to keep track of.
