### ISSUE TITLE
Make keyboard

### ISSUE THREAD

**Issue by nagesh66542** [AppGround-io/bluetooth-keyboard-and-mouse-support#60]
make a keyboard with all keys of query Ctrl f1 alt media keys or enable to change keyboard for this app from installed keyboards.

**Comment by zorazor** [comment]
You can create a custom key-set with shortcuts.
F1-F12, alt, ctrl, shift, tab and coplex button combos.

**Comment by AppGround-io** [comment]
Closing because shortcuts can be used for this
