### ISSUE TITLE
[Feature Request] Option to disable the direct/input-field bar (incl. solving bug)

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-keyboard-and-mouse-support#63]
Hello,
can you add an option to disable the new direct/input-field bar, please?

I often use the keyboard and shortcuts together. With this new bar the remaining screen/mouse area is in my case unfortunately a bit too small.

**Comment by zorazor** [comment]
Workaround-Bug:
1. start the app and activate the keyboard.
2. press the android square and tap straightaway again on the app.
3. the new direct/input-field bar is hidden/disabled.

**Comment by AppGround-io** [comment]
This bar is not my favorite and I would like to find a better solution for it, so maybe it will change in the next release. 
But if I don't find a better solution, I will add an option to disable the bar it in the next feature release.

**Comment by zorazor** [comment]
Thank you! The new menu in v2.15.1 is really great.
