### ISSUE TITLE
Feature Vanished: "Paste from Android clipboard"?

### ISSUE THREAD

**Issue by tgi007** [AppGround-io/bluetooth-keyboard-and-mouse-support#65]
Beginning with version 2.13.1 (updated last night, from 2.13.0 which works fine):

What happened to "paste from (Android) clipboard" function? It's no longer on the menu, and the "Paste" button at bottom of screen (when "Show shortcuts" is enabled) is merely a synonym for the target computer's native "paste" (its own clipboard) function.

I use this capability very often, particularly for capturing barcode scans (on the Android phone), then pasting into PC's database software.

How do I now paste from Android's clipboard to target system?

This used to be the last item "Paste clipboard text" on the "gear" menu.

For now I will revert to prior version.

Google Pixel 3XL
Android 9
Build PQ2A 109305.002

**Comment by zorazor** [comment]
You have to paste your clipboard into the new keyboard-bar respectively into the input-text field since the last update.

**Comment by zorazor** [comment]
I like that idea. The shortcuts bar has a lot of potential for productivity.

**Comment by AppGround-io** [comment]
Paste button is now in input bar and you can make is always visible in the settings
