### ISSUE TITLE
Surface-like 2nd finger clicks

### ISSUE THREAD

**Issue by PrototypeNM1** [AppGround-io/bluetooth-keyboard-and-mouse-support#68]
**Is your feature request related to a problem? Please describe.**
Clicking a small button is difficult because touching the screen is likely to move the cursor.

**Describe the solution you'd like**
Like a Surface touchpad, I would like to left click by touching the screen with a second finger while the first finger is still down having moved the cursor. Any position change from the second finger should be ignored for this action.

**Additional context**
Being able to click with a second finger while moving with the first is really useful for other actions such as click and drag, but just being able to click is really useful as the first finger "anchors" the mouse position. This makes clicking small elements much easier than clicking with one finger, which is likely to slightly reposition the mouse.

**Comment by AppGround-io** [comment]
This is like a really good idea! 
How do you right click, with three fingers?

**Comment by PrototypeNM1** [comment]
Thinking on it a bit more, if you had a touch pressure click (in addition to the tap and release click), you might be able to solve the same problem with one finger. Essentially this would just be checking the touch pressure and clicking when it's above a threshold, releasing when it's under, and vibration to indicate both click and release. This would also likely need a pressure dead zone between click and release to prevent rapidly clicking at the transition between click and release.

**Comment by AppGround-io** [comment]
Clicking with the second finger is now supported in the current version
