### ISSUE TITLE
Horizontal scrolling options: sensitivity and invert

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-keyboard-and-mouse-support#69]
**Is your feature request related to a problem? Please describe.**
1. Horizontal scrolling is too slow.
2. Horizontal scrolling should be invertible.

**Describe the solution you'd like**
Add a separate sensitivity slider and an invert checkbox, please.

**Comment by Genxster1998** [comment]
+1

**Comment by Mi-Sanchez** [comment]
The App scroll speed option has no effect on the side scrolling at all. Only up and down.

Any Windows users have the same problem when side swiping with two fingers? I have only Ubuntu (Linux) installed.

**Comment by Mi-Sanchez** [comment]
I was now able to test it also on Windows and there is the same issue.

The current App scroll speed option only affects the horizontal speed and ignores vertical scrolling.

The lable should be changed from enhancement to bug.
