### ISSUE TITLE
Can't pair my device.

### ISSUE THREAD

**Issue by nickgrserifos** [AppGround-io/bluetooth-keyboard-and-mouse-support#71]
Can't pair my device. It's connected with my Bluetooth Android device but it doesn't pair. I have an OnePlus Nord device. I had no issues with my previous pixel 2 device but with my new device I tried everything but still nothing.

**Comment by BahadirKaya90** [comment]
Install the 2.5.0 version and enable  "compatibility mode" to pair your devices. After pairing devices disable compatibility mode again in order your your mouse to work correctly. After that you can update app to a latest version but latest one has issues like back button does not work and there is no compatibility mode.

**Comment by Polisson** [comment]
Hm... if only problem exists in Android libraries and with v9+ is doable (standard mode is used), then maybe there is a workaround using Magisk or EdXposed on controlling device? Some kind of patch?
