### ISSUE TITLE
Cannot simulate left button press and scroll up/down

### ISSUE THREAD

**Issue by vivekdeal** [AppGround-io/bluetooth-keyboard-and-mouse-support#72]
**Describe the bug**
Cannot simulate left mouse button press and move up and down to scroll

**To Reproduce**
1. Go to chrome or any browser
2. Visit any dite that does not fit in screen and needs you to scroll up and down
3. On a regular mouse, you can keep left key pressed and scroll up and down
4. Try doing it on the app, you can move the mouse but not scroll (so it is like the left button is not even pressed). I tried placing one finger on left to simulate the button press and tried moving. Didn't work. 
5. Also delete (backspace) button does not work when typing. Not filing another bug for it right now. 

**Expected behavior**
Should be able to keep one finger on left side to simulate key press and move the mouse. This will allow scrolling and dragging. 

**Screenshots**

**Additional context**
I have purchased the premium version. My email on the purchase is viveksethi@gmail.com

**Comment by AppGround-io** [comment]
Please let me know if this is still a problem with the current version of the app.
