### ISSUE TITLE
Bluetooth speaker

### ISSUE THREAD

**Issue by HISOKA1997** [AppGround-io/bluetooth-keyboard-and-mouse-support#73]
Hello. I want to put forward a suggestion if you can implement it in the same context as linking a mouse or keyboard. I want to add a feature to connect a speaker, meaning to make the phone turn into an audio output for another device via Bluetooth. Thank you

**Comment by AppGround-io** [comment]
Thank you for the suggestion. Bluetooth has many different profiles and turning your device into a Bluetooth speaker is not supported by Android, so it's not possible to implement this feature.
