### ISSUE TITLE
Option to disable edge-scrolling

### ISSUE THREAD

**Issue by denilsonsa** [AppGround-io/bluetooth-keyboard-and-mouse-support#74]
On every touchpad of every laptop I use, I disable the "edge scrolling" (i.e. single-finger scrolling by moving at the edge of the touchpad). Since the touchpads support two-finger scrolling this feature can be safely disabled for my uses.

In special, edge-scrolling means the touchpad will send scroll events when I meant to just move the mouse pointer. Very frustrating. Even worse because the edge area is not marked in any way.

## Proposed solution

* Option to enable/disable edge scrolling.
    * Optionally a slider to define how thick this area is; but this slider might be too much, so I'm fine not having it.
* If edge scrolling is enabled, it must be visible on the virtual touchpad. (Draw a rectangle, a line, or something.)

## Additional context

This is related (and somewhat opposite) to what #21 asked. In fact, #21 asked for three things in one issue, making it difficult to track anything.

**Comment by zorazor** [comment]
Version 2.17 has new options for scrolling.

I have a dual-edge curved screen and until this version, scrolling along the rounded edge was perfect. I'm a bit sad now that the area has been enlarged so much and is no longer optimized for my device ;-(

**Comment by AppGround-io** [comment]
The size of the scroll box was changed from a percentage of the screen to a fixed size in version 2.18.0 and should be back to its old size on the phone.
