### ISSUE TITLE
Meta / Win Key Shortcut

### ISSUE THREAD

**Issue by myuubie** [AppGround-io/bluetooth-keyboard-and-mouse-support#77]
Hi there,

I tried creating a shortcut for the Meta key (I assume this is the Win/Command key) for my Windows 10 PC but it doesn't seem to do anything. I want to be able to just press the Win key by itself to bring up my Start menu.

Thanks.

![Screenshot_20200914-192628_Bluetooth Keyboard   Mouse](https://user-images.githubusercontent.com/9543955/93080491-5812c400-f6c0-11ea-8c8b-799eb586c6b2.jpg)

**Comment by AdamKane41** [comment]
Hey,
Try **[CTRL]** + **[ESC]** ... It will open the "Start Menu" on Every versions of Windows. :)
Peace

**Comment by AppGround-io** [comment]
Thank you for reporting the problem. This was a bug and is now fixed with the newest version 2.16.1.
