### ISSUE TITLE
Feature Request: Additional keys for shortcuts, e.g. Sleep, etc. 

### ISSUE THREAD

**Issue by myuubie** [AppGround-io/bluetooth-keyboard-and-mouse-support#79]
**Is your feature request related to a problem? Please describe.**
My heavy keyboard has a Sleep button which I use to put the pc to sleep, but it's a bit tiresome to get off my couch to get to it and having to make sure to turn off its wireless connection to the pc before it wakes up again. XD 

**Describe the solution you'd like**
Would be nice to have these kind of keys available in the shortcuts so that I can just put em to sleep on my phone. 😬 

Thanks a lot!

**Comment by AppGround-io** [comment]
In custom mode there are now more keys available, e.g Power Off
