### ISSUE TITLE
Unable to purchase Premium Paid Version :(

### ISSUE THREAD

**Issue by AdamKane41** [AppGround-io/bluetooth-keyboard-and-mouse-support#8]
Hey, will the Premium Paid Version become available for purchase in every Region/Location? Because i'm unable to buy it in the Google App Store or via in-app purchase. I can only unlock for 1h with Ads... I am in Montreal/Québec/Canada. Peace
¯——_—_—-==¯——_—_—-==¯——_—_—-==
![Screenshot_2019-11-03-09-31-27-1](https://user-images.githubusercontent.com/30092603/68087499-b9bd9d00-fe24-11e9-8a7c-0242c5092bd9.png)

¯——_—_—-==¯——_—_—-==¯——_—¯——_—_—-=—-==

**Comment by Jadelor** [comment]
This non-inapp-purchase version isn't available in Finland either. Got the in-app premium, but why isn't this available?

**Comment by AdamKane41** [comment]
@Jadelor After posting my situation over here and also as a "review" on the google app store, maybe a couple of days later the Premium version poped up on the play store and the purchase button became available in my country.
The purchase went through without problem. It works great, all features and no more videos. The premium version is its own seperate app so its not like those cheap "fake' purchases that only adds a 1 or 0 in the code to bypass the ads... Pur clean code yummmm. 
Peace

**Comment by AppGround-io** [comment]
For tax reasons the premium version is not available in some countries. If a country is still missing, let me know and I will look into it.
