### ISSUE TITLE
[Feature Request] Spoof the phone device type

### ISSUE THREAD

**Issue by parkerlreed** [AppGround-io/bluetooth-keyboard-and-mouse-support#80]
**Is your feature request related to a problem? Please describe.**

Android TV/Google TV only shows input devices/game controllers. Since the phone still shows up as a phone, it never shows up when scanning from Android/Google TV.

**Describe the solution you'd like**

If possible, have the application change the Bluetooth device type to keyboard/mouse.

**Comment by AppGround-io** [comment]
You can now connect to Chromecast with Google TV by entering the MAC address of the Chromecast in the app connection screen.
