### ISSUE TITLE
ChromeOS support?

### ISSUE THREAD

**Issue by biarritx** [AppGround-io/bluetooth-keyboard-and-mouse-support#81]
Hello,

I'm adapting a Chromebook for a friend with disabilities.
I would like to use his phone to program the following shortcuts :
- Alt+Shift+s (ChromeVox)
- Super+s (Select-to-speak)
- Super+d (Speak-to-type)
- Ctrl+plus (Chrome zoom in)
- Ctrl+minus (Chrome zoom out)
- Ctrl+Shift+plus (Screen zoom in)
- Ctrl+Shift+minus (Screen zoom out)

According to its description, the "Serverless Bluetooth Keyboard" supports Chromebook/ChromeOS.BUT, I do not manage his phone (and mine) to his Chromebook. It looks like BT phone pairing is not supported by ChromeOS. Can you help us?

Thanks a lot.
Jérôme

**Comment by AppGround-io** [comment]
Bluetooth on many Chrome OS devices does not work very good, if the pairing does not work it means that the device is not supported.
