### ISSUE TITLE
Compatibility mode is broken

### ISSUE THREAD

**Issue by Pawloland** [AppGround-io/bluetooth-keyboard-and-mouse-support#82]
At the beginning  I would like to ask you to read this bug report fully, before closing it with saying something along the lines of "compatibility mode isn't guaranteed to work". I already know this, but you have made some changes along the way and **compatibility mode isn't working anymore**.

**Describe the bug**
Receiver device:                 Sony Xperia Z3 Compact (Lineage 17.1 - android 10, Bluetooth v4.0 - supports normal mode)
Device with app installed (transmitter) : Sony Xperia M4 Aqua (stock android 6, Bluetooth v4.1 - doesn't support normal mode)

Version 1.12.0 (47) of free app is the last version with working compatibility mode. I checked different newer versions and all of them have not working compatibility mode.
I have purchased premium app to use premium features, but sadly I can't use them since the compatibility mode isn't working with latest v2.18.1 premium version.

**To Reproduce**
1. Remove devices from connected devices on receiver and transmitter device.
2. Open old free app v1.12.0
3. On receiver device connect to transmitter device and walk through connection dialogs on both devices.
4. Old app works using compatibility mode, receiver device is controlled with app on transmitter device.

5. Remove devices from connected devices on receiver and transmitter device.
2. Open premium app v2.18.1.
3. On receiver device connect to transmitter device and walk through connection dialogs on both devices.
4. Devices are initially paired and connected, but only for just a second. Then devices are disconnected and receiver device can not be connected to transmitter device and thus receiver can not be controlled using latest v2.18.1 premium app.

**Expected behavior**
Receiver device should connect to transmitter device, and receiver device should be able to be controlled through latest premium app v2.18.1, using compatibility mode.

**Screenshots**
Not a screenshot, but a screen recording of two devices side by side showing the problem, as it occurs. On the left is transmitter (M4 Aqua), on the right is receiver (Z3 Compact).
https://youtu.be/PhCayzUZfqU

**Additional context**
I discovered that with latest version of premium app v2.18.1 opened, on receiver device I sometimes see two different entries of the device to connect (telephone and input device) while with old free app v1.12.0, on receiver device I see only one entry - input device. This might be helpful observation used for debugging this issue.

**Comment by wstlxx** [comment]
HI, can you share the old free apk ,because my current phone with compatibility mode is not able to reconnect, needs a all over pairing every time. I wonder if the old release help.
And is there a list of phones supporting standard mode? because if my op5 won't work anyway, i'll consider looking for a new phone

**Comment by Pawloland** [comment]
I am side loading older versions from apk pure. This site has android app, from where you can download and install older releases (it supports apk an apks format). Keep in mind that I also always unpaired devices from each other and cleared app data, in order to get working connection. Reconnection never worked for me with compatibility mode (but it isn't much of a problem for me, since I find it more important to app acctually work at all. I am used to this little inconvenience, and tolerate it, because it guarantees, that connection will work 100% times.

**Comment by AppGround-io** [comment]
Thank for the detailed description of the problem. 

There were a lot of changes between 1.12 and the current version to improve the connection for the compatibility mode. But each improvement that fixes one device may break a another. The goal is always to have the highest possible compatibility with all devices.

I created a version where it's possible to change some parameters of the connection behavior. 

https://play.google.com/apps/test/RQos6v6bJIA/ahAOU_83iWShRFt0rTTDqOAzzNMwS6IMe0KHZ2LRqXo6a8-IQwdYcMRW3WeeFsGkQ1vHM__DfICk-gLEngEzS83V1G

You can try first each option individually and then combinations if it's not working.

**Comment by Pawloland** [comment]
I will test it as soon as I have spare time, so I think somewhere around this weekend (if nothing unexpected happends). U can expect some response info about this test version around that time, but I can't guarantee it for sure.

**Comment by Pawloland** [comment]
I tried to install this beta version but it isn't installing on my m4 aqua. I suspect it may be because of missing component of split apk, for my architecture? Idk.
![Screenshot_20201015-151544.png](https://user-images.githubusercontent.com/59684145/96132071-3c3a5200-0efa-11eb-8f71-2103720faf60.png)

I also tried to install it on my z3 compact and it was installed successfully, but after opening, app immediately closes, but I can see for split second new menu at the top.

Until those issues are not fixed I am unable to further test this version.

**Comment by AppGround-io** [comment]
I created a new version that fixes the start crash on newer Android versions:

https://play.google.com/apps/test/RQos6v6bJIA/ahAOU_83g9zciDUR7Ozcy_z0XgVV-wbFcvb4O4xAuVVo_s3LBXrC5IDw0UR47J_rlklOoNcVxZW0vP5e6HUBFNb1e_

Not sure what the problem with the installation could be, it's the same app bundle that is used for normal releases as well. Maybe not enough storage available?

**Comment by Pawloland** [comment]
OK, I downloaded version 2.19.0-dev2 on my z3 Compact and it is no longer crashing at startup. I also resolved issue with google play store not installing v2.19.0-dev2 on m4 aqua by clearing and force stopping those apps:
-google play store
-google play services
-google 
-google services for instant apps
-webview
and uninstalling updates of google play store, rebooting device, waiting for play store to auto update to latest version, installing commonly available free version of an app from play store, heading to the 2.19.0-dev2 install page, uninstalling at the time installed free version of an app from install screen of 2.19.0-dev2 and FINALLY SUCCESSFULLY installing 2.19.0-dev2 on m4 Aqua, where app also isn't crashing at startup. I am not sure which step was crucial for it to work, so I am writing all of them in case someone has the same problem. 

Now I have a few questions about mechanism behind those newly added check buttons a, b and c:
1. Can they be selected more than 1 (two or three at the time) or will it result in guaranteed failure/crash, or only last selected will be used?
2. Can they be not selected at all or will it result in guaranteed failure/crash, or will it default to something?
3. Does sequence of selecting/ deselecting those check buttons has any effect?
4. Are they supposed to be used only before establishing connections?
5. If it is not secret what exactly each of them do? I suspect they work as switches to some variables/ functions used inside app's logic to tweak connection handshake, but I would like to know what is the desired effect of selecting a, b or/and c depending if more than one check button can be selected (or rather should be, because when I used the v2.19.0-dev2 , more than one could be selected, but I don't know if it is intended by you  behavior or it's like that because you didn't want to write extra logic for that for now and assumed only one or none would be selected at once).

Answers to those questions would be highly helpful for me while creating and doing my test cases for 2.19.0-dev2 to give you the most detailed test results I possibly can.
Cheers 😉

**Comment by AppGround-io** [comment]
The options are just flags to trigger a specify behavior int the code, the sequence does not matter. Everything deselected is the default behavior from the current Play Store version. 

All flags are only for solving initial connection problems, so they have to be activated before connecting/pairing.

Option A: Activation means disabling a workaround for remote devices that do not recognize the keyboard and mouse correctly.
Option B: Restart Bluetooth after bonding
Option C: Refresh connection after connecting

You can just select one or all at once, this will not break the app and combination may be needed to make the connection work.

**Comment by Pawloland** [comment]
### I made some tests and here are my results (after every connection I unpaired devices from each other and cleared app's data):

<table>
        <thead>
          <tr>
            <th scope="col" colspan="3">Options</th>
            <th scope="col" rowspan="3">Results</th>
          </tr>
          <tr></tr>
          <tr>
            <th scope="col" >A</th>
            <th scope="col">B</th>
            <th scope="col">C</th>
          </tr>
        </thead>
        <tbody>
        <tr></tr>
          <tr>
            <td scope="row"></td>
            <td></td>
            <td></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"><b>X</b></td>
            <td></td>
            <td></td>
            <td>Pairing is successful, <ins><b>connection is established, bt mouse and keyboard is working</b></ins>, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"></td>
            <td><b>X</b></td>
            <td></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"></td>
            <td></td>
            <td><b>X</b></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"><b>X</b></td>
            <td><b>X</b></td>
            <td></td>
            <td>Pairing is successful, <ins><b>connection is established, bt mouse and keyboard is working</b></ins>, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"><b>X</b></td>
            <td></td>
            <td><b>X</b></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"></td>
            <td><b>X</b></td>
            <td><b>X</b></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
          <tr>
            <td scope="row"><b>X</b></td>
            <td><b>X</b></td>
            <td><b>X</b></td>
            <td>Pairing is successful, connection is established, immediately after it's lost, reconnection doesn't work, new pairing is needed</td>
          </tr>
        </tbody>
      </table>

Additional observations: 

- once the connection is working in compatibility mode (case with just A option or options AB) it is easily lost. It occurs while app is in idle (touchpad isn't used by a user nor keyboard is used inside app on transmitter device) or when changing keyboard layout on receiver device. I can't point my finger on which one of those reasons exactly is causing loss in connection between devices, but it occurs most often when I was not using transmitter device and while simultaneously changing keyboard layout on receiver device (using directly touch screen of receiver device). Shortly after changing the layout connection was lost, if transmitter device was not sending anything to receiver for past few seconds (connection loss wasn't always the case thought). It wasn't only time it happened thought. It also happened when app was just in idle for between 5 to 15 seconds, but it also didn't happened always, so it would be idle for 30 seconds and work just fine, but on different try it would work only for 10 seconds and then disconnect. It is hard for me to define what is the problem here, but I can definitely define that <b>there IS  a problem</b>.


- once the connection is lost either by the bug (I don't know if it can be classified as an app's bug or some sort of interference of outer world) or by the unsuccessful handshake between devices, reconnecting never have worked with compatibility mode. I think it is because between resets of the bt or reopening the app, causes the bt MAC address that app uses to appear as input device is different than one used while pairing (and the actual bt MAC address of the device, but as I understand it is necessary to high jack real MAC address or else you wouldn't be able to show transmitter device as input device and it would show as normally as phone, while receiver devices searches for it ), so when app tries to connect to receiver device, it always fails, because it appears with new MAC address, so receiver doesn't allow it to connect thinking it is completely different device. I also observed similar behavior on my receiver device, it also changes bt MAC (different discoverable MAC address than the actual bt MAC address of the device) it uses to pair between restart of bt. I am blue in terms of Bluetooth protocol, so I can be dead wrong saying this hypothesis, but as far as I know MAC randomization is a thing only in LAN devices, not BT devices, so those differentiating bt MAC addresses might be key to solving the problem.

By summing all those information I can say, that this version indeed fixed my initial connection problems, that didn't happened on older versions and now I am more or less able to also use compatibility mode without major issues (expect random, unpredictable disconnections and need to create new pairing after every disconnection) and I can say for sure this:

<i><b>Maaaan, you need to add those changes to new public releases of free and premium versions ASAP for new people to check them out 😎</b></i><sup>1</sup> 

<sub>1. Just add the info you gave me what those options A, B and C are meant to do.</sub>

**Comment by AppGround-io** [comment]
Thank you for detailed investigation of this issue, much appreciated. The problem with connection loss is probably interference with other devices and there is not much I can do about it since the connecting is handled by the system and and the Bluetooth firmware. 

The random MAC address is indeed a problem with reconnecting, but it's not possible to change the behavior in the app. But reconnecting is still possible with many devices, and there still some things I want to try out to fix this problem. 

I will add a setting to change only the option A in the app soon, since the other two are not as effective also from my testing. 

Thanks again for the help!

**Comment by Pawloland** [comment]
I am on premium v2.21.1 and the switch for option A is still not there. When will it be merged to public premium version?

**Comment by AppGround-io** [comment]
I'm still thinking of the best way to do this. I don't want to confuse users with an option they don't understand. This would only result in frustration on the user side and support efforts on my part.

I will try to find a solution for the next version, maybe for end of the month.

**Comment by Pawloland** [comment]
After the next two weeks it is still not implemented in premium v2.21.2. I can't deny that I am annoyed at this point, because one and a half of month, in my opinion is enough time to implement this toogle already, given that the bug was already identified and fixed in a test version of an app. 

Can you please, add this buton, so I can use this app again with all it's premium features?
This option can be burried deep down in the settings, so I and potentially a few other people, who are using github and are aware of the issue, can make use of it.
You wouldn't have to worry about constant questions for support, since typical user wouldn't be even aware of it, while you could in the meantime make proper implementation of this feature, that suits your UI and UX standars, while I can use premium features.
Please do it. It's win win win situation.

**Comment by AppGround-io** [comment]
The version v2.21.2 was an unplanned bugfix release to fix a critical problem with the keyboard, the next feature version v2.22.0 will contain the option for the compatibility mode. This version will be released in one or two weeks, sorry for the delay.
