### ISSUE TITLE
Left mouse button or OK button does not work inside my web mail aol in chrome navigator android tv.

### ISSUE THREAD

**Issue by jjae6** [AppGround-io/bluetooth-keyboard-and-mouse-support#86]
Hi, i purchased recently your product. Good product.

I have a Bug report:
- From chrome browser of my android tv, I enter in my AOL web mail: "http://mail.aol.com"
- I cannot select different folders: INBOX, DRAFTS, SENT ... because the "ok button" or "left mouse button" does not work. 
- In the web navigator Address bar it does work and I can put a link and press ok for example, but not inside navigator.
Note:  With my physical remote control, ok button works in mouse mode and I can switch between folders..but not through your application, they do not work to select internal elements of the browser.

B/R
![not-selectable](https://user-images.githubusercontent.com/74360243/98943615-12238200-24f0-11eb-8551-187e28e3d6a0.jpg)

**Comment by AppGround-io** [comment]
Please let me know if this still a problem with the current version of the app.
