### ISSUE TITLE
does it work with the new google chromecast? 

### ISSUE THREAD

**Issue by jorge25years** [AppGround-io/bluetooth-keyboard-and-mouse-support#90]
Just in my case, It does not detect the bluetooth keyboard...
And I bought the complete version of this app.

Can anybody help me with that?
Thanks very much in advance

**Comment by AdamKane41** [comment]
What is the "New Chromecast"? A)Chromecast + Google TV or B)Chromecast Ultra?
I just bought a Chromecast + Google TV, i will experiment with BleK to see whats up. Also, what keyboard do you have on your Phone and in your chrimecast? Peace

**Comment by AppGround-io** [comment]
Chromecast with Google TV is supported by the current version
