### ISSUE TITLE
Unsupported version of app

### ISSUE THREAD

**Issue by Madhav1969** [AppGround-io/bluetooth-keyboard-and-mouse-support#96]
Whenever i open the app it says unsupported version and i am anable to use it. I think the app is up to date(version. 3.0.2).please see the attached image
![Screenshot_20210114_122044](https://user-images.githubusercontent.com/77430616/104555080-45ef6500-5663-11eb-9b97-e227bc651d92.jpg)

**Comment by AppGround-io** [comment]
Should be fixed now, please let me know if this is still a problem.
